### PR TITLE
Fixes to make guide work on 2.8

### PR DESCRIPTION
**Pull request by rp-julienguery**

### CODE REVIEW

**Comment by awholegunch** [comment]
Please check if these are to be merged to "cdap-2.8.0-compatible" or "cdap-2.8-compatible". As the release branch is release/2.8, it should be kept the same.

**Comment by albertshau** [comment]
Thanks for bringing that up @awholegunch. We are going to change the branches to be cdap-2.8-compatible so let's hold off on this until those branches are up.

**Comment by rp-julienguery** [comment]
@awholegunch @albertshau can't we just make that change of branch name after I merge those PRs?

**Comment by albertshau** [comment]
thats fine, lgtm

**Comment by albertshau** [comment]
though actually, the other branch was already created. let's just reopen instead of merging here then merging again.

**Pull request closed without merging**
